---
Name: silverstripe-localdate
After: 'framework/*'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\ORM\FieldType\DBDate:
    class: LocalDate\LocalDate;
  SilverStripe\ORM\FieldType\DBDatetime:
    class: LocalDate\LocalDatetime;
  SilverStripe\ORM\FieldType\DBTime:
    class: LocalDate\LocalTime;
